<?php
// REMOVE MAGIC QUOTES!!!
if (get_magic_quotes_gpc()) {
	$process = array(&$_GET, &$_POST, &$_COOKIE, &$_REQUEST);
	while (list($key, $val) = each($process)) {
		foreach ($val as $k => $v) {
			unset($process[$key][$k]);
			if (is_array($v)) {
				$process[$key][stripslashes($k)] = $v;
				$process[] = &$process[$key][stripslashes($k)];
			} else {
				$process[$key][stripslashes($k)] = stripslashes($v);
			}
		}
	}
	unset($process);
}
// ENABLE NOTICES FOR DEBUGGING
ini_set('display_errors', 1);
error_reporting(E_ALL);

// SET TIMEZONE
date_default_timezone_set('America/New_York');
?>